Final-Project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::resource('genres', GenreController::class)->except(['index', 'show']);
    Route::resource('movies', MovieController::class)->except(['index', 'show']);
    Route::resource('reviews', ReviewController::class);
});

Route::resources([
    'genres' => GenreController::class,
    'movies' => MovieController::class
], ['only' => ['index', 'show']]);

Final-Project/resources/views/pages/movies/create.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Tambah Movie')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <form action="{{ route('movies.store') }}" method="POST">
                    @csrf
                    <div class="form-group mt-3">
                        <label for="title">Judul</label>
                        <input type="text" class="form-control" id="title" name="title" required>
                    </div>
                    <div class="form-group mt-3">
                        <label for="release_date">Tanggal Rilis</label>
                        <input type="date" class="form-control" id="release_date" name="release_date" required>
                    </div>
                    <div class="form-group mt-3">
                        <label for="description">Deskripsi</label>
                        <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                    </div>
                    <div class="form-group mt-3">
                        <label for="genre_id">Genre</label>
                        <select class="form-control" id="genre_id" name="genre_id" required>
                            <option value="">Pilih Genre</option>
                            @foreach($genres as $genre)
                                <option value="{{ $genre->id }}">{{ $genre->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                    <a href="{{ route('movies.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

Final-Project/resources/views/pages/movies/edit.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Edit Movie')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <form action="{{ route('movies.update', $movie->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group mt-3">
                        <label for="title">Judul</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ $movie->title }}" required>
                    </div>
                    <div class="form-group mt-3">
                        <label for="release_date">Tanggal Rilis</label>
                        <input type="date" class="form-control" id="release_date" name="release_date" value="{{ $movie->release_date }}" required>
                    </div>
                    <div class="form-group mt-3">
                        <label for="description">Deskripsi</label>
                        <textarea class="form-control" id="description" name="description" rows="3" required>{{ $movie->description }}</textarea>
                    </div>
                    <div class="form-group mt-3">
                        <label for="genre_id">Genre</label>
                        <select class="form-control" id="genre_id" name="genre_id" required>
                            <option value="">Pilih Genre</option>
                            @foreach($genres as $genre)
                                <option value="{{ $genre->id }}" {{ $movie->genre_id == $genre->id ? 'selected' : '' }}>{{ $genre->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                    <a href="{{ route('movies.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

Final-Project/resources/views/pages/movies/index.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Movie')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <h6 class="mb-10">
                    <a href="{{ route('movies.create') }}" class="btn btn-primary mb-3">Tambah Data</a>
                </h6>
                <div class="table-wrapper table-responsive-sm">
                    <table id="example" class="table" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Title</th>
                                <th>Release Date</th>
                                <th>Genre</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($movies as $movie)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $movie->title }}</td>
                                <td>{{ $movie->release_date }}</td>
                                <td>{{ $movie->genre->name }}</td>
                                <td class="text-center">
                                    <a href="{{ route('movies.show', $movie->id) }}" class="btn btn-info "><i class="mdi mdi-eye-outline"></i></a>
                                    <a href="{{ route('movies.edit', $movie->id) }}" class="btn btn-warning"><i class="mdi mdi-pencil-outline"></i></a>
                                    <form action="{{ route('movies.destroy', $movie->id) }}" method="POST" style="display: inline-block;">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-outline"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $('form').submit(function(event) {
        event.preventDefault();
        Swal.fire({
            title: 'Apakah Anda yakin?',
            text: "Data yang dihapus tidak dapat dikembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!',
            cancelButtonText: 'Batal'
        }).then((result) => {
            if (result.isConfirmed) {
                $(this).unbind('submit').submit();
            }
        });
    });
</script>
@endpush

Final-Project/resources/views/pages/movies/show.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Detail Movie')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                    <table class="table">
                        <tr>
                            <th>Judul</th>
                            <td>{{ $movie->title }}</td>
                        </tr>
                        <tr>
                            <th>Tanggal Rilis</th>
                            <td>{{ $movie->release_date }}</td>
                        </tr>
                        <tr>
                            <th>Deskripsi</th>
                            <td>{{ $movie->description }}</td>
                        </tr>
                        <tr>
                            <th>Genre</th>
                            <td>{{ $movie->genre->name }}</td>
                        </tr>
                    </table>
                    <a href="{{ route('movies.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </div>
                <div class="row">
                    @foreach($reviews as $review)
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ $review->user->name }}</h5>
                                <div class="rating mb-2">
                                    @for($i = 1; $i <= 5; $i++)
                                        @if($i <= $review->rating)
                                            <span class="text-warning"><i class="lni lni-star-fill"></i></span>
                                        @else
                                            <span class="text-muted"><i class="lni lni-star-fill"></i></span>
                                        @endif
                                    @endfor
                                </div>
                                <p class="card-text">{{ $review->review_text }}</p>
                                @if($review->review_note)
                                    <p class="card-text"><small class="text-muted">Catatan: {{ $review->review_note }}</small></p>
                                @endif
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                <div class="card-style mb-30">
                    <h4>Tulis Review</h4>
                    <form action="{{ route('reviews.store') }}" method="POST" class="mt-4">
                        @csrf
                        <div class="form-group mt-3">
                            <label for="rating">Rating</label>
                            <div class="rating">
                                <input type="radio" id="star1" name="rating" value="1" /> <label for="star1" title="1 star">★</label><br>
                                <input type="radio" id="star2" name="rating" value="2" /> <label for="star2" title="2 stars">★★</label><br>
                                <input type="radio" id="star3" name="rating" value="3" /> <label for="star3" title="3 stars">★★★</label><br>
                                <input type="radio" id="star4" name="rating" value="4" /> <label for="star4" title="4 stars">★★★★</label><br>
                                <input type="radio" id="star5" name="rating" value="5" /> <label for="star5" title="5 stars">★★★★★</label>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <label for="review_text">Review</label>
                            <textarea name="review_text" id="review_text" class="form-control" rows="3"></textarea>
                        </div>
                        <div class="form-group mt-3">
                            <label for="review_note">Catatan</label>
                            <textarea name="review_note" id="review_note" class="form-control" rows="2"></textarea>
                        </div>
                        <input type="hidden" name="movie_id" value="{{ $movie->id }}">
                        <input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
                        <input type="hidden" name="genre_id" value="{{ $movie->genre->id }}">
                        <button type="submit" class="btn btn-primary mt-3">Kirim Review</button>
                    </form>
                </div>                
            </div>
            </div>
        </div>
    </div>
</section>
@endsection