Final-Project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::resource('genres', GenreController::class)->except(['index', 'show']);
    Route::resource('movies', MovieController::class)->except(['index', 'show']);
    Route::resource('reviews', ReviewController::class);
});

Route::resources([
    'genres' => GenreController::class,
    'movies' => MovieController::class
], ['only' => ['index', 'show']]);

Final-Project/resources/views/layouts/partials/footer.blade.php
<footer class="footer">
<div class="container-fluid">
    <div class="row">
    <div class="col-md-6 order-last order-md-first">
        <div class="copyright text-center text-md-start">
        <p class="text-sm">
            Muhammad Ridho Rabbani Rachman - Sanbercode Laravel Batch 57
        </p>
        </div>
    </div>
    <!-- end col-->
    </div>
    <!-- end row -->
</div>
<!-- end container -->
</footer>

Final-Project/resources/views/layouts/partials/header.blade.php
<header class="header">
<div class="container-fluid">
    <div class="row">
    <div class="col-lg-5 col-md-5 col-6">
        <div class="header-left d-flex align-items-center">
        <div class="menu-toggle-btn mr-15">
            <button id="menu-toggle" class="main-btn primary-btn btn-hover">
            <i class="mdi mdi-menu me-2"></i> Menu
        </button>
        </div>
        </div>
    </div>
    <div class="col-lg-7 col-md-7 col-6">
        <div class="header-right">
        <!-- notification end -->
        <!-- profile start -->
        <div class="profile-box ml-15">
            <button class="dropdown-toggle bg-transparent border-0" type="button" id="profile"
            data-bs-toggle="dropdown" aria-expanded="false">
            <div class="profile-info">
                <div class="info">
                <div class="image">
                    <img src="assets/images/profile/profile-image.png" alt="" />
                </div>
                <div>
                    <h6 class="fw-500 text-capitalize">{{ Auth::user()->name }}</h6>
                    <p>{{ Auth::user()->username }}</p>
                </div>
                </div>
            </div>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile">
            <li>
                <div class="author-info flex items-center !p-1">
                <div class="image">
                    <img src="assets/images/profile/profile-image.png" alt="image">
                </div>
                <div class="content">
                    <h4 class="text-sm">{{ Auth::user()->name }}</h4>
                    <a class="text-black/40 dark:text-white/40 hover:text-black dark:hover:text-white text-xs"
                    href="#">{{ Auth::user()->email }}</a>
                </div>
                </div>
            </li>
            <li class="divider"></li>
            <li class="divider"></li>
            <li>
                @csrf
                <a href="{{ route('logout') }}"
                onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
                    <i class="line-icon-exit"></i> Sign Out </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                    @csrf
                </form>
            </li>
            </ul>
        </div>
        <!-- profile end -->
        </div>
    </div>
    </div>
</div>
</header>

Final-Project/resources/views/layouts/partials/sidebar.blade.php
<aside class="sidebar-nav-wrapper">
<div class="navbar-logo">
    <a href="index.html">
    <img src="{{ asset('assets/images/logo/logo.svg') }}" alt="logo" />
    </a>
</div>
<nav class="sidebar-nav">
    <ul>
    <li class="nav-item">
        <a href="{{ route('home') }}">
            <span class="icon me-3">
            <i class="mdi mdi-view-dashboard"></i>
        </span>
        <span class="text">Dashboard</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('genres.index') }}">
            <span class="icon me-3">
            <i class="mdi mdi-movie"></i>
        </span>
        <span class="text">Genre</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{{ route('movies.index') }}">
            <span class="icon me-3">
            <i class="mdi mdi-play-circle"></i>
        </span>
        <span class="text">Movie</span>
        </a>
    </li>
    </ul>
</nav>
</aside>