Final-Project/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\GenreController;
use App\Http\Controllers\CastController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ReviewController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    
    Route::resource('genres', GenreController::class)->except(['index', 'show']);
    Route::resource('movies', MovieController::class)->except(['index', 'show']);
    Route::resource('reviews', ReviewController::class);
});

Route::resources([
    'genres' => GenreController::class,
    'movies' => MovieController::class
], ['only' => ['index', 'show']]);

Final-Project/app/Models/Genre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Genre extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function movie()
    {
        return $this->hasMany(Movie::class);
    }
}

Final-Project/app/Http/Controllers/GenreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use RealRashid\SweetAlert\Facades\Alert;

class GenreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $genres = Genre::all();
        return view('pages.genres.index', compact('genres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.genres.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' =>'required|max:255',
        ]);

        DB::transaction(function () use ($validated) {
            Genre::create([
                'name' => $validated['name'],
            ]);
        });

        Alert::success('Sukses', 'Data telah dibuat');

        return redirect()->route('genres.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function show(Genre $genre)
    {
        $genre->load('movie');

        return view('pages.genres.show', compact('genre'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function edit(Genre $genre)
    {
        return view('pages.genres.edit', compact('genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Genre $genre)
    {
        $validated = $request->validate([
            'name' =>'required|max:255',
        ]);

        DB::transaction(function () use ($validated, $genre) {
            $genre->update([
                'name' => $validated['name'],
            ]);
        });

        Alert::success('Sukses', 'Data telah diubah');

        return redirect()->route('genres.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Genre  $genre
     * @return \Illuminate\Http\Response
     */
    public function destroy(Genre $genre)
    {
        Alert::success('Sukses', 'Data telah dihapus');
        $genre->delete();
        return redirect()->route('genres.index');
    }
}

Final-Project/resources/views/pages/genres/create.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Genre')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <form action="{{ route('genres.store') }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Submit</button>
                    <a href="{{ route('genres.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

Final-Project/resources/views/pages/genres/edit.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Genre')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <form action="{{ route('genres.update', $genre->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $genre->name }}" required>
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">Update</button>
                    <a href="{{ route('genres.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

Final-Project/resources/views/pages/genres/index.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Genre')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                <h6 class="mb-10">
                    <a href="{{ route('genres.create') }}" class="btn btn-primary mb-3">Tambah Data</a>
                </h6>
                <div class="table-wrapper table-responsive-sm">
                    <table id="example" class="table" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($genres as $genre)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $genre->name }}</td>
                                <td class="text-center">
                                    <a href="{{ route('genres.show', $genre->id) }}" class="btn btn-info "><i class="mdi mdi-eye-outline"></i></a>
                                    <a href="{{ route('genres.edit', $genre->id) }}" class="btn btn-warning"><i class="mdi mdi-pencil-outline"></i></a>
                                    <form action="{{ route('genres.destroy', $genre->id) }}" method="POST" style="display: inline-block;">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger"><i class="mdi mdi-delete-outline"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script>
    $(document).ready(function() {
        $('#example').DataTable();
    } );
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $('form').submit(function(event) {
        event.preventDefault();
        Swal.fire({
            title: 'Apakah Anda yakin?',
            text: "Data yang dihapus tidak dapat dikembalikan!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ya, hapus!',
            cancelButtonText: 'Batal'
        }).then((result) => {
            if (result.isConfirmed) {
                $(this).unbind('submit').submit();
            }
        });
    });
</script>
@endpush

Final-Project/resources/views/pages/genres/show.blade.php
@extends('layouts.master')

@section('content')
<section class="table-components">
    <div class="container-fluid">
        @section('title', 'Detail Genre')
        
        <div class="tables-wrapper">
            <div class="row">
            <div class="col-lg-12">
                <div class="card-style mb-30">
                    <h3>{{ $genre->name }}</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Judul Film</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if($genre->movie->isEmpty())
                                <tr>
                                    <td colspan="2">Tidak ada film</td>
                                </tr>
                            @else
                                @foreach($genre->movie as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->title }}</td>
                                </tr>
                                @endforeach
                            @endif                        </tbody>
                    </table>
                    <a href="{{ route('genres.index') }}" class="btn btn-secondary mt-3">Kembali</a>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
@endsection